services:
    opensearch:
        container_name: opensearch
        hostname: opensearch
        image: opensearchproject/opensearch:1.3.17
        restart: always
        ports:
            - 9200:9200
            - 9600:9600
        volumes:
            - ./data:/usr/share/opensearch/data:delegated
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
            - "DISABLE_SECURITY_PLUGIN=true"
            - "discovery.type=single-node"
            - "cluster.routing.allocation.disk.watermark.low=5mb"
            - "cluster.routing.allocation.disk.watermark.high=2mb"
            - "cluster.routing.allocation.disk.watermark.flood_stage=1mb"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536

        networks:
            - opensearch-net

    opensearch-dashboards:
        container_name: opensearch-dashboards
        hostname: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:1.3.0
        restart: always
        ports:
            - 5601:5601
        expose:
            - "5601"
        environment:
            - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
            - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
        networks:
            - opensearch-net

volumes:
    opensearch-data1:

networks:
    opensearch-net:

